### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by ray-x** [jbyuki/lua-debug.nvim#1]
Hi, I am trying to set it up to debug my nvim lua plugins.
suppose I am trying to debug lua_test.lua. Flowed the instruction in README.md
I will open lua_test.lua in nvim instance 1 and run launch. it will echo a port (e.g. 64929) debug server is on.
In another nvim open lua_test.lua. and run `lua require'dap'.countine`. I will be ask to input the debug server port. 
But after I input the port. There is no message to indicate I connected to the server or not. If I run `require'dap'.continue, I saw `no stopped thread, Can not move`

Is anything missed in my steps?

**Comment by jbyuki** [comment]
Hi,

All you did is correct. In order to see the debugger in action you will need to:

1. Put a breakpoint using `require"dap".toggle_breapoint()` in you dap neovim instance (in `lua_test.lua`).
2. Launch lua-debug in the other instance
2. Tell dap to continue, at the same time connect to the server.
3. Run `lua_test.lua` in the server instance (where lua-debug was launched). For example using `:luafile lua_test.lua`
4. The breakpoint should hit and freeze the other instance.

The procedure is the same for neovim plugins. Tell me if it works.

**Comment by jbyuki** [comment]
I added a message which notifies when nvim-dap connects to lua-debug. Hopefully this should make it more clear.

**Comment by ray-x** [comment]
I followed your steps and it works now. It would be good to update the README.md as well. Thanks!
